DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USERTOKENS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS MOVEMENTS;

CREATE TABLE USERS (
    USERNAME VARCHAR(8) PRIMARY KEY,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    USERROLE VARCHAR(15) NOT NULL,
    LOCKED BOOLEAN NOT NULL,
    ENABLED BOOLEAN NOT NULL
);

CREATE TABLE USERTOKENS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TOKEN VARCHAR(250) NOT NULL,
    CREATEDAT TIMESTAMP NOT NULL,
    EXPIRESAT TIMESTAMP NOT NULL,
    CONFIRMEDAT TIMESTAMP,
    USERNAME VARCHAR(8) NOT NULL
);

CREATE TABLE PRODUCTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(8) UNIQUE NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(100),
    QUANTITY INT NOT NULL,
    PRICE NUMERIC(10, 2) NOT NULL
);

CREATE TABLE MOVEMENTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL,
    USERNAME VARCHAR(8) NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    DESCRIPTION VARCHAR(100),
    PRODUCT INT NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE NUMERIC(10, 2) NOT NULL,
    STATUS BOOLEAN NOT NULL
);

ALTER TABLE USERTOKENS ADD FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME);
ALTER TABLE MOVEMENTS ADD FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME);
ALTER TABLE MOVEMENTS ADD FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID);